import type { VendorDetail } from './types';

export const demoVendorDetails: Record<string, VendorDetail> = {
  v1: {
    id: 'v1',
    name: 'Valley Greens',
    code: 'VG-001',
    status: 'active',
    contact: { email: 'orders@valleygreens.example', phone: '(404) 555-0132' },
    paymentTermCode: 'NET30',
    leadDays: 2,
    minimumOrderAmount: '$250.00',
    hasOperatingProfile: true,
    openOrderCount: 1,
    openAmounts: [{ currency: 'USD', value: '$2,140.00' }],
    canReadCost: true,
  },
  v2: {
    id: 'v2',
    name: 'Southern Poultry Co',
    code: 'SPC-014',
    status: 'active',
    contact: { email: 'ap@southernpoultry.example', phone: '(912) 555-0188' },
    paymentTermCode: 'NET15',
    leadDays: 3,
    minimumOrderAmount: null,
    hasOperatingProfile: true,
    openOrderCount: 1,
    openAmounts: [{ currency: 'USD', value: '$2,514.00' }],
    canReadCost: true,
  },
  v3: {
    id: 'v3',
    name: 'Peachtree Dairy',
    code: 'PD-007',
    status: 'active',
    contact: { email: null, phone: '(678) 555-0199' },
    paymentTermCode: 'NET30',
    leadDays: 1,
    minimumOrderAmount: null,
    hasOperatingProfile: true,
    openOrderCount: 0,
    openAmounts: [],
    canReadCost: true,
  },
};
